@startuml

participant MailServer
participant MailFilter
participant FanFilter
participant SpamFilter
participant BusinessFilter

MailServer -> MailFilter

group filters
    MailFilter --> FanFilter
    FanFilter --> MailFilter
    FanFilter --> SpamFilter
    SpamFilter --> FanFilter
    SpamFilter --> BusinessFilter
    BusinessFilter --> SpamFilter

end

MailFilter --> MailServer

@enduml